config/routes.rb
Rails.application.routes.draw do
  resources :frens
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fren.rb
class Fren < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frens_controller.rb
class FrensController < ApplicationController
  before_action :set_fren, only: %i[ show edit update destroy ]

  # GET /frens or /frens.json
  def index
    @frens = Fren.all
  end

  # GET /frens/1 or /frens/1.json
  def show
  end

  # GET /frens/new
  def new
    @fren = Fren.new
  end

  # GET /frens/1/edit
  def edit
  end

  # POST /frens or /frens.json
  def create
    @fren = Fren.new(fren_params)

    respond_to do |format|
      if @fren.save
        format.html { redirect_to fren_url(@fren), notice: "Fren was successfully created." }
        format.json { render :show, status: :created, location: @fren }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fren.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frens/1 or /frens/1.json
  def update
    respond_to do |format|
      if @fren.update(fren_params)
        format.html { redirect_to fren_url(@fren), notice: "Fren was successfully updated." }
        format.json { render :show, status: :ok, location: @fren }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fren.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frens/1 or /frens/1.json
  def destroy
    @fren.destroy

    respond_to do |format|
      format.html { redirect_to frens_url, notice: "Fren was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fren
      @fren = Fren.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fren_params
      params.require(:fren).permit(:first_name, :last_name, :email)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frens_helper.rb
module FrensHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frens/_form.html.erb
<%= form_with(model: fren) do |form| %>
  <% if fren.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fren.errors.count, "error") %> prohibited this fren from being saved:</h2>

      <ul>
        <% fren.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/frens/_fren.html.erb
<div id="<%= dom_id fren %>">
  <p>
    <strong>First name:</strong>
    <%= fren.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= fren.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= fren.email %>
  </p>

</div>

app/views/frens/edit.html.erb
<h1>Editing fren</h1>

<%= render "form", fren: @fren %>

<br>

<div>
  <%= link_to "Show this fren", @fren %> |
  <%= link_to "Back to frens", frens_path %>
</div>

app/views/frens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Frens</h1>

<div id="frens">
  <% @frens.each do |fren| %>
    <%= render fren %>
    <p>
      <%= link_to "Show this fren", fren %>
    </p>
  <% end %>
</div>

<%= link_to "New fren", new_fren_path %>

app/views/frens/new.html.erb
<h1>New fren</h1>

<%= render "form", fren: @fren %>

<br>

<div>
  <%= link_to "Back to frens", frens_path %>
</div>

app/views/frens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fren %>

<div>
  <%= link_to "Edit this fren", edit_fren_path(@fren) %> |
  <%= link_to "Back to frens", frens_path %>

  <%= button_to "Destroy this fren", @fren, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">

  <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "ABOUT US", home_about_path, class:"nav-link" %>
        </li>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      <form class="d-flex" role="search">
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
 ABOUT US.....

app/views/home/index.html.erb
<h1>Hello World!!</h1>
This is my first rails web page

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    <%= render "home/header" %>
    <div class="container">
    <%=yield%>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>